### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by iayanami** [Jaammerr/python_sui_sdk#1]
hey man, i use code:

from pysdk_sui import Client, Wallet, RpcDetails, WalletInfoParams, MoveCallParams, TransferObjectParams, GetTransactionsIDParams, MoveFunctionArgTypesParams

faucet_url_ = 'https://faucet.testnet.sui.io/gas'
rpc_url_ = 'https://fullnode.testnet.sui.io/'
test_mnemonic = 'trip offer end cloth patrol core pioneer debate cigar swarm patch tattoo'

client = Client(rpc_url=rpc_url_, faucet_url=faucet_url_, mnemonic=test_mnemonic)
wallet = Wallet(rpc_url=rpc_url_, faucet_url=faucet_url_, mnemonic=test_mnemonic)
rpc = RpcDetails(rpc_url=rpc_url_, faucet_url=faucet_url_, mnemonic=test_mnemonic)

def create_wallet():
    # generate wallet (return NamedTuple with mnemonic, private key, public key and address)
    for i in range(10):
        wallet_data = wallet.generate_wallet()
        print (wallet_data)
        
create_wallet()

and i get mistake:

AttributeError: module 'bip_utils' has no attribute 'Bip32Slip10Ed25519'

**Comment by Jaammerr** [comment]
Hello! Just checked your code - everything works fine. Check version of bip_utils and see if the module is installed correctly
